### ISSUE TITLE
panic if verifying with incorrect leaf count

### ISSUE THREAD

**Issue by themighty1** [antouhou/rs-merkle#20]
When verifying a proof, we rely on the Prover (a potentially malicious party in our case) to inform the Verifier about the correct number of the leaves in the tree. Trying to verify with an incorrect number causes a panic.

Can be reproduced by modifying a line in this example: https://github.com/antouhou/rs-merkle/blob/8ffa623ce70a3659ae73619397b813887cd8d1c9/src/merkle_proof.rs#L155
and changing the last arg to `leaves.len() + 100`

**Comment by antouhou** [comment]
Thank you for the report, I'll look into it!
